name: eatery_components
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.2 < 3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  file_picker: ^5.2.0+1
  path_parsing: ^1.0.1
  flutter_svg: ^2.0.7
  eatery_db:
    path: "../eatery_db"
  eatery_services:
    path: "../eatery_services"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/vectors/
    - assets/